# Generated by Django 5.2.4 on 2025-07-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yangiliklar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='news_image/'),
        ),
    ]
