# Generated by Django 5.2.4 on 2025-07-08 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yangiliklar', '0002_alter_new_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='picture',
            new_name='image',
        ),
    ]
