# Generated by Django 5.2.4 on 2025-07-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yangiliklar', '0003_rename_picture_new_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
