# Generated by Django 5.2.4 on 2025-07-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yangiliklar', '0004_alter_category_slug_alter_new_slug_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='news_image/'),
        ),
    ]
