# Generated by Django 5.2.4 on 2025-07-12 05:07

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yangiliklar', '0008_advertisement'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='advertisement',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
