# Generated by Django 5.2.4 on 2025-07-12 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yangiliklar', '0009_alter_advertisement_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='advertisement',
            managers=[
            ],
        ),
    ]
