# Generated by Django 5.2.4 on 2025-07-12 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yangiliklar', '0010_alter_advertisement_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='new',
            managers=[
            ],
        ),
    ]
