# Generated by Django 5.2.4 on 2025-07-17 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yangiliklar', '0011_alter_new_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
