# Generated by Django 5.2.4 on 2025-07-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yangiliklar', '0012_remove_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
