# Generated by Django 5.2.4 on 2025-07-17 17:43

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yangiliklar', '0013_alter_contact_full_name_alter_contact_subject'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comments',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
