# Generated by Django 5.2.4 on 2025-07-19 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yangiliklar', '0017_alter_new_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='start_time',
        ),
    ]
