# Generated by Django 5.2.4 on 2025-07-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yangiliklar', '0018_remove_advertisement_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
